[run]
init_cmds = [
	["go","run","bin/build.go","-v"],
		["./builds/0.0.1/aurora"]
]						# Commands run in start
watch_all = true		# Watch all sub-directories
watch_dirs = [
	"$WORKDIR/bin",
	"$WORKDIR/cmd"
]
watch_exts = [".go",".html",".js",".css"]
build_delay = 1500		# Minimal interval to Trigger build event
cmds = [
	["goimports","-w=true","."],
	["godep","go","run","bin/build.go","-v"],
	["./builds/0.0.1/aurora"]

]

[sync]
listen_addr = ":5050"
remote_addr = ":5050"